---
# tasks file for Dell-Networking.dellos-aaa

 - name: "Generating AAA configuration for dellos9"
   template:
      src: dellos9_aaa.j2
      dest: "{{ build_dir }}/aaa9_{{hostname}}.conf.part"
   when: (ansible_network_os is defined and ansible_network_os == "dellos9") and ((dellos_cfg_generate | default('False')) | bool)
#   notify: save config os9
   register: generate_output

 - name: "Provisioning AAA configuration for dellos9"
   dellos9_config:
      src: dellos9_aaa.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos9")
#   notify: save config os9
   register: output

 - name: "Generating AAA configuration for dellos10"
   template:
      src: dellos10_aaa.j2
      dest: "{{ build_dir }}/aaa10_{{hostname}}.conf.part"
   when: (ansible_network_os is defined and ansible_network_os == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)
#   notify: save config os10
   register: generate_output

 - name: "Provisioning AAA configuration for dellos10"
   dellos10_config:
      src: dellos10_aaa.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos10") 
#   notify: save config os10
   register: output

